#!/usr/bin/env node
'use strict';
/**
 * Builds the Encounters in Joy blog.
 *
 *   blog/posts/*.md            (written by the CMS at /admin/, or by hand)
 *         │
 *         ▼
 *   blog/index.html            list of published posts
 *   blog/<slug>/index.html     one page per post
 *   blog/feed.xml              RSS feed
 *   sitemap.xml                blog URLs refreshed between the blog:start/blog:end markers
 *
 * Netlify runs this on every deploy (see netlify.toml), so the generated
 * files are NOT committed to git (see .gitignore). To preview locally:
 *
 *     node tools/build-blog.js
 *
 * No npm install needed — marked (Markdown → HTML) and js-yaml (front matter)
 * are vendored in tools/vendor/.
 *
 * A post is skipped (with a warning, never a failed build) if it has no
 * title/date or its front matter can't be parsed. Posts marked `draft: true`
 * are skipped silently so authors can save work-in-progress.
 */

const fs = require('fs');
const path = require('path');
const marked = require('./vendor/marked.umd.js');
const yaml = require('./vendor/js-yaml.min.js');
const T = require('./blog-templates.js');

const ROOT = path.resolve(__dirname, '..');
const BLOG_DIR = path.join(ROOT, 'blog');
const POSTS_DIR = path.join(BLOG_DIR, 'posts');
const SITEMAP = path.join(ROOT, 'sitemap.xml');
const ON_NETLIFY = process.env.NETLIFY === 'true';
const GENERATED_MARK = '<!-- generated by tools/build-blog.js — do not edit; edit blog/posts/*.md instead -->';

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

marked.use({ gfm: true, breaks: false });

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function warn(msg) {
  console.warn('  ⚠  ' + msg);
}

/** Split "---\n<yaml>\n---\n<markdown>" into { data, body }. */
function parseFrontMatter(raw) {
  const text = raw.replace(/^﻿/, '').replace(/\r\n/g, '\n');
  const m = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(text);
  if (!m) return null;
  return { data: yaml.load(m[1]) || {}, body: m[2] };
}

/** Normalise whatever the YAML gave us into a "YYYY-MM-DD" string. */
function toIsoDate(value) {
  if (value instanceof Date && !isNaN(value)) return value.toISOString().slice(0, 10);
  if (typeof value === 'string') {
    const s = value.trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;
    const d = new Date(s);
    if (!isNaN(d)) return d.toISOString().slice(0, 10);
  }
  return null;
}

function longDate(iso) {
  const [y, m, d] = iso.split('-').map(Number);
  return `${MONTHS[m - 1]} ${d}, ${y}`;
}

function rfcDate(iso) {
  return new Date(iso + 'T12:00:00Z').toUTCString();
}

/** URL slug from a file name: "2026-09-01-my-post.md" or "my-post.md" → "my-post". */
function slugFromFile(file) {
  return (
    path
      .basename(file, '.md')
      .replace(/^\d{4}-\d{2}-\d{2}-/, '')
      .toLowerCase()
      .normalize('NFKD')
      .replace(/[^\x00-\x7F]/g, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'post'
  );
}

function stripTags(html) {
  return html
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

function truncate(text, max) {
  if (text.length <= max) return text;
  const cut = text.slice(0, max);
  return cut.slice(0, Math.max(cut.lastIndexOf(' '), 40)).replace(/[,;:.\-–—]+$/, '') + '…';
}

/**
 * Image URL helper. On Netlify, same-site images are routed through the
 * Image CDN so a 6 MB phone photo uploaded through the CMS is served resized
 * and compressed. Locally (and for external URLs) the path is used as-is.
 */
function imageUrl(src, opts) {
  if (!src) return '';
  if (!ON_NETLIFY || /^https?:\/\//i.test(src)) return encodeURI(src);
  const q = new URLSearchParams({ url: src });
  if (opts && opts.w) q.set('w', String(opts.w));
  if (opts && opts.h) q.set('h', String(opts.h));
  if (opts && opts.fit) q.set('fit', opts.fit);
  q.set('q', '75');
  return '/.netlify/images?' + q.toString();
}

/** Route inline <img> tags in the rendered body through the image CDN and lazy-load them. */
function optimiseBodyImages(html) {
  return html.replace(/<img\b([^>]*?)\bsrc="([^"]+)"([^>]*)>/g, (whole, before, src, after) => {
    const attrs = (before + after).replace(/\s+/g, ' ');
    const lazy = /\bloading=/.test(attrs) ? '' : ' loading="lazy" decoding="async"';
    return `<img${before}src="${imageUrl(src, { w: 1200 })}"${after}${lazy}>`;
  });
}

// ---------------------------------------------------------------------------
// Read + validate posts
// ---------------------------------------------------------------------------

function readPosts() {
  if (!fs.existsSync(POSTS_DIR)) {
    fs.mkdirSync(POSTS_DIR, { recursive: true });
    return { published: [], drafts: 0 };
  }

  const files = fs
    .readdirSync(POSTS_DIR)
    .filter((f) => f.toLowerCase().endsWith('.md'))
    .sort();

  const published = [];
  const usedSlugs = new Set();
  let drafts = 0;

  for (const file of files) {
    const rel = path.posix.join('blog/posts', file);
    let parsed;
    try {
      parsed = parseFrontMatter(fs.readFileSync(path.join(POSTS_DIR, file), 'utf8'));
    } catch (err) {
      warn(`${rel}: could not read front matter (${err.message}) — skipped`);
      continue;
    }
    if (!parsed) {
      warn(`${rel}: no front matter block found — skipped`);
      continue;
    }

    const d = parsed.data;
    if (d.draft === true) {
      drafts++;
      continue;
    }

    const title = String(d.title == null ? '' : d.title).trim();
    const dateIso = toIsoDate(d.date);
    if (!title) {
      warn(`${rel}: missing title — skipped`);
      continue;
    }
    if (!dateIso) {
      warn(`${rel}: missing or unreadable date — skipped`);
      continue;
    }

    let slug = slugFromFile(file);
    if (usedSlugs.has(slug)) {
      let n = 2;
      while (usedSlugs.has(`${slug}-${n}`)) n++;
      warn(`${rel}: URL /blog/${slug}/ is already taken — using /blog/${slug}-${n}/`);
      slug = `${slug}-${n}`;
    }
    usedSlugs.add(slug);

    const html = optimiseBodyImages(marked.parse(parsed.body || ''));
    const plain = stripTags(html);
    const wordCount = plain ? plain.split(' ').length : 0;
    const summary = String(d.summary == null ? '' : d.summary).replace(/\s+/g, ' ').trim();
    const url = `/blog/${slug}/`;

    published.push({
      file,
      slug,
      url,
      absoluteUrl: T.SITE + url,
      title,
      author: String(d.author == null ? '' : d.author).trim() || 'Encounters in Joy',
      dateIso,
      dateLong: longDate(dateIso),
      dateRfc: rfcDate(dateIso),
      summary,
      excerpt: summary || truncate(plain, 160),
      image: d.image ? String(d.image).trim() : '',
      html,
      wordCount,
      readingMinutes: Math.max(1, Math.round(wordCount / 200)),
    });
  }

  published.sort((a, b) => (a.dateIso < b.dateIso ? 1 : a.dateIso > b.dateIso ? -1 : a.title.localeCompare(b.title)));
  return { published, drafts };
}

// ---------------------------------------------------------------------------
// Write output
// ---------------------------------------------------------------------------

function writeFile(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content, 'utf8');
}

function withMark(html) {
  return html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + GENERATED_MARK);
}

/** Remove pages for posts that were deleted or turned back into drafts. */
function removeStalePages(keep) {
  for (const entry of fs.readdirSync(BLOG_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === 'posts' || keep.has(entry.name)) continue;
    const dir = path.join(BLOG_DIR, entry.name);
    const index = path.join(dir, 'index.html');
    if (!fs.existsSync(index)) continue;
    if (!fs.readFileSync(index, 'utf8').includes(GENERATED_MARK)) continue; // not ours — leave it
    fs.rmSync(index);
    if (fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
  }
}

function updateSitemap(posts) {
  if (!fs.existsSync(SITEMAP)) {
    warn('sitemap.xml not found — skipped sitemap update');
    return;
  }
  const START = '  <!-- blog:start — generated by tools/build-blog.js, do not edit by hand -->';
  const END = '  <!-- blog:end -->';
  const today = new Date().toISOString().slice(0, 10);
  const newest = posts.length ? posts[0].dateIso : today;

  const entry = (loc, lastmod, changefreq, priority) =>
    `  <url>\n    <loc>${loc}</loc>\n    <lastmod>${lastmod}</lastmod>\n    <changefreq>${changefreq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`;

  const block = [
    START,
    entry(T.SITE + '/blog/', newest, 'weekly', '0.7'),
    ...posts.map((p) => entry(p.absoluteUrl, p.dateIso, 'monthly', '0.6')),
    END,
  ].join('\n');

  const xml = fs.readFileSync(SITEMAP, 'utf8');
  const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(escapeRe(START) + '[\\s\\S]*?' + escapeRe(END));
  const next = re.test(xml) ? xml.replace(re, block) : xml.replace(/\s*<\/urlset>/, '\n' + block + '\n</urlset>');
  if (next !== xml) fs.writeFileSync(SITEMAP, next, 'utf8');
}

function main() {
  console.log(`Building blog${ON_NETLIFY ? ' (Netlify)' : ''}…`);
  const { published, drafts } = readPosts();

  for (const p of published) {
    const others = published.filter((o) => o !== p);
    writeFile(path.join(BLOG_DIR, p.slug, 'index.html'), withMark(T.postPage(p, others, imageUrl)));
  }
  writeFile(path.join(BLOG_DIR, 'index.html'), withMark(T.indexPage(published, imageUrl)));
  writeFile(path.join(BLOG_DIR, 'feed.xml'), T.feed(published));
  removeStalePages(new Set(published.map((p) => p.slug)));
  updateSitemap(published);

  console.log(`  ✓ ${published.length} post${published.length === 1 ? '' : 's'} published` + (drafts ? `, ${drafts} draft${drafts === 1 ? '' : 's'} skipped` : ''));
  for (const p of published) console.log(`    ${p.url}  ←  blog/posts/${p.file}`);
}

main();
